
DATASET_DIR = "data"
TRAIN_VAL_SPLIT_RATIO = 0.95
BATCH_SIZE = 64
LEARNING_RATE = 1e-4
EPOCHS = 40
HIDDEN_SIZE = 32
MIN_ACCURACY = .45
TEST_DATA_ROOT = "data/test"
LABEL_FILE_PATH = "classes.txt"
CLASSIFICATION_API_PORT = 9000